"""Build the DiceMed desktop executable (PyInstaller, one-folder) and the Inno Setup script.

    python build_app.py            # requires models/dicemed_density_v2.pt
"""
import os
import shutil
import subprocess
import sys

BUNDLE = os.path.join("models", "dicemed_density_v2.pt")

SPEC = r'''# -*- mode: python ; coding: utf-8 -*-
# Generated by build_app.py - edit there.
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

datas = [
    ('Background.png', '.'),
    ('bgcolour.png', '.'),
    ('models/dicemed_density_v2.pt', 'models'),
    ('MODEL_CARD.md', '.'),
]
datas += collect_data_files('customtkinter')
datas += collect_data_files('timm')

a = Analysis(
    ['Interface.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=['customtkinter', 'PIL.ImageTk', 'cv2', 'sklearn.metrics', 'sklearn.covariance']
                  + collect_submodules('mammo') + collect_submodules('timm.models'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'pandas', 'pyarrow', 'IPython', 'jupyter'],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name='DiceMed', debug=False, strip=False, upx=False,
          console=False)
coll = COLLECT(exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=False, name='DiceMed')
'''

ISS = r'''; Generated by build_app.py
[Setup]
AppName=DiceMed
AppVersion=2.0
DefaultDirName={autopf}\DiceMed
DefaultGroupName=DiceMed
OutputBaseFilename=DiceMedSetup
OutputDir=Output
Compression=lzma2
SolidCompression=yes
DisableDirPage=auto

[Files]
Source: "dist\DiceMed\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\DiceMed"; Filename: "{app}\DiceMed.exe"
Name: "{commondesktop}\DiceMed"; Filename: "{app}\DiceMed.exe"
'''


def main():
    if not os.path.exists(BUNDLE):
        sys.exit(f"Missing {BUNDLE}. Train/export the model first (see README.md).")
    for d in ("build", "dist"):
        if os.path.exists(d):
            shutil.rmtree(d)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt", "pyinstaller"])
    with open("DiceMed.spec", "w") as f:
        f.write(SPEC)
    with open("installer.iss", "w") as f:
        f.write(ISS)
    subprocess.check_call([sys.executable, "-m", "PyInstaller", "DiceMed.spec", "--clean", "--noconfirm"])
    print("\nBuilt dist/DiceMed/DiceMed.exe. Compile installer.iss with Inno Setup to create the installer.")


if __name__ == "__main__":
    main()
