# -*- mode: python ; coding: utf-8 -*-
# Generated by build_app.py - edit there.
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

datas = [
    ('Background.png', '.'),
    ('bgcolour.png', '.'),
    ('models/dicemed_density_v2.pt', 'models'),
    ('MODEL_CARD.md', '.'),
]
datas += collect_data_files('customtkinter')
datas += collect_data_files('timm')

a = Analysis(
    ['Interface.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=['customtkinter', 'PIL.ImageTk', 'cv2', 'sklearn.metrics', 'sklearn.covariance']
                  + collect_submodules('mammo') + collect_submodules('timm.models'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'pandas', 'pyarrow', 'IPython', 'jupyter'],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name='DiceMed', debug=False, strip=False, upx=False,
          console=False)
coll = COLLECT(exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=False, name='DiceMed')
