; Generated by build_app.py
[Setup]
AppName=DiceMed
AppVersion=2.0
DefaultDirName={autopf}\DiceMed
DefaultGroupName=DiceMed
OutputBaseFilename=DiceMedSetup
OutputDir=Output
Compression=lzma2
SolidCompression=yes
DisableDirPage=auto

[Files]
Source: "dist\DiceMed\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\DiceMed"; Filename: "{app}\DiceMed.exe"
Name: "{commondesktop}\DiceMed"; Filename: "{app}\DiceMed.exe"
